//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WServicioAutos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos
    {
        public System.Guid ID_Auto { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string anio_Fabricacion { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public string Color { get; set; }
    }
}
