//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formprin.ServiceReferenceAutos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autos", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Autos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid ID_AutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string anio_FabricacionField;
        
        private System.Nullable<decimal> PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid ID_Auto {
            get {
                return this.ID_AutoField;
            }
            set {
                if ((this.ID_AutoField.Equals(value) != true)) {
                    this.ID_AutoField = value;
                    this.RaisePropertyChanged("ID_Auto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Marca {
            get {
                return this.MarcaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaField, value) != true)) {
                    this.MarcaField = value;
                    this.RaisePropertyChanged("Marca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string anio_Fabricacion {
            get {
                return this.anio_FabricacionField;
            }
            set {
                if ((object.ReferenceEquals(this.anio_FabricacionField, value) != true)) {
                    this.anio_FabricacionField = value;
                    this.RaisePropertyChanged("anio_Fabricacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAutos.WebServiceAutosSoap")]
    public interface WebServiceAutosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerAutosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerAutos", ReplyAction="*")]
        Formprin.ServiceReferenceAutos.ObtenerAutosResponse ObtenerAutos(Formprin.ServiceReferenceAutos.ObtenerAutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerAutos", ReplyAction="*")]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ObtenerAutosResponse> ObtenerAutosAsync(Formprin.ServiceReferenceAutos.ObtenerAutosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _marca del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarAuto", ReplyAction="*")]
        Formprin.ServiceReferenceAutos.InsertarAutoResponse InsertarAuto(Formprin.ServiceReferenceAutos.InsertarAutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.InsertarAutoResponse> InsertarAutoAsync(Formprin.ServiceReferenceAutos.InsertarAutoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        Formprin.ServiceReferenceAutos.ModificarResponse Modificar(Formprin.ServiceReferenceAutos.ModificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Modificar", ReplyAction="*")]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ModificarResponse> ModificarAsync(Formprin.ServiceReferenceAutos.ModificarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAuto", ReplyAction="*")]
        Formprin.ServiceReferenceAutos.EliminarAutoResponse EliminarAuto(Formprin.ServiceReferenceAutos.EliminarAutoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarAuto", ReplyAction="*")]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.EliminarAutoResponse> EliminarAutoAsync(Formprin.ServiceReferenceAutos.EliminarAutoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _marca del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMarca", ReplyAction="*")]
        Formprin.ServiceReferenceAutos.ObtenerMarcaResponse ObtenerMarca(Formprin.ServiceReferenceAutos.ObtenerMarcaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerMarca", ReplyAction="*")]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ObtenerMarcaResponse> ObtenerMarcaAsync(Formprin.ServiceReferenceAutos.ObtenerMarcaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAutosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAutos", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.ObtenerAutosRequestBody Body;
        
        public ObtenerAutosRequest() {
        }
        
        public ObtenerAutosRequest(Formprin.ServiceReferenceAutos.ObtenerAutosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerAutosRequestBody {
        
        public ObtenerAutosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerAutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerAutosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.ObtenerAutosResponseBody Body;
        
        public ObtenerAutosResponse() {
        }
        
        public ObtenerAutosResponse(Formprin.ServiceReferenceAutos.ObtenerAutosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerAutosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Formprin.ServiceReferenceAutos.Autos[] ObtenerAutosResult;
        
        public ObtenerAutosResponseBody() {
        }
        
        public ObtenerAutosResponseBody(Formprin.ServiceReferenceAutos.Autos[] ObtenerAutosResult) {
            this.ObtenerAutosResult = ObtenerAutosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAuto", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.InsertarAutoRequestBody Body;
        
        public InsertarAutoRequest() {
        }
        
        public InsertarAutoRequest(Formprin.ServiceReferenceAutos.InsertarAutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _marca;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _modelo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _anio_fabricacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal _precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string _color;
        
        public InsertarAutoRequestBody() {
        }
        
        public InsertarAutoRequestBody(string _marca, string _modelo, string _anio_fabricacion, decimal _precio, string _color) {
            this._marca = _marca;
            this._modelo = _modelo;
            this._anio_fabricacion = _anio_fabricacion;
            this._precio = _precio;
            this._color = _color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarAutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarAutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.InsertarAutoResponseBody Body;
        
        public InsertarAutoResponse() {
        }
        
        public InsertarAutoResponse(Formprin.ServiceReferenceAutos.InsertarAutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarAutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertarAutoResult;
        
        public InsertarAutoResponseBody() {
        }
        
        public InsertarAutoResponseBody(bool InsertarAutoResult) {
            this.InsertarAutoResult = InsertarAutoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Modificar", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.ModificarRequestBody Body;
        
        public ModificarRequest() {
        }
        
        public ModificarRequest(Formprin.ServiceReferenceAutos.ModificarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _marcaM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string _modeloM;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string _anio_fabricacionM;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal _precioM;
        
        public ModificarRequestBody() {
        }
        
        public ModificarRequestBody(string _id, string _marcaM, string _modeloM, string _anio_fabricacionM, decimal _precioM) {
            this._id = _id;
            this._marcaM = _marcaM;
            this._modeloM = _modeloM;
            this._anio_fabricacionM = _anio_fabricacionM;
            this._precioM = _precioM;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.ModificarResponseBody Body;
        
        public ModificarResponse() {
        }
        
        public ModificarResponse(Formprin.ServiceReferenceAutos.ModificarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModificarResult;
        
        public ModificarResponseBody() {
        }
        
        public ModificarResponseBody(bool ModificarResult) {
            this.ModificarResult = ModificarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarAutoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarAuto", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.EliminarAutoRequestBody Body;
        
        public EliminarAutoRequest() {
        }
        
        public EliminarAutoRequest(Formprin.ServiceReferenceAutos.EliminarAutoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarAutoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _id;
        
        public EliminarAutoRequestBody() {
        }
        
        public EliminarAutoRequestBody(string _id) {
            this._id = _id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EliminarAutoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EliminarAutoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.EliminarAutoResponseBody Body;
        
        public EliminarAutoResponse() {
        }
        
        public EliminarAutoResponse(Formprin.ServiceReferenceAutos.EliminarAutoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EliminarAutoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool EliminarAutoResult;
        
        public EliminarAutoResponseBody() {
        }
        
        public EliminarAutoResponseBody(bool EliminarAutoResult) {
            this.EliminarAutoResult = EliminarAutoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMarcaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMarca", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.ObtenerMarcaRequestBody Body;
        
        public ObtenerMarcaRequest() {
        }
        
        public ObtenerMarcaRequest(Formprin.ServiceReferenceAutos.ObtenerMarcaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerMarcaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _marca;
        
        public ObtenerMarcaRequestBody() {
        }
        
        public ObtenerMarcaRequestBody(string _marca) {
            this._marca = _marca;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerMarcaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerMarcaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Formprin.ServiceReferenceAutos.ObtenerMarcaResponseBody Body;
        
        public ObtenerMarcaResponse() {
        }
        
        public ObtenerMarcaResponse(Formprin.ServiceReferenceAutos.ObtenerMarcaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerMarcaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ObtenerMarcaResult;
        
        public ObtenerMarcaResponseBody() {
        }
        
        public ObtenerMarcaResponseBody(string ObtenerMarcaResult) {
            this.ObtenerMarcaResult = ObtenerMarcaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAutosSoapChannel : Formprin.ServiceReferenceAutos.WebServiceAutosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAutosSoapClient : System.ServiceModel.ClientBase<Formprin.ServiceReferenceAutos.WebServiceAutosSoap>, Formprin.ServiceReferenceAutos.WebServiceAutosSoap {
        
        public WebServiceAutosSoapClient() {
        }
        
        public WebServiceAutosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAutosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAutosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAutosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formprin.ServiceReferenceAutos.ObtenerAutosResponse Formprin.ServiceReferenceAutos.WebServiceAutosSoap.ObtenerAutos(Formprin.ServiceReferenceAutos.ObtenerAutosRequest request) {
            return base.Channel.ObtenerAutos(request);
        }
        
        public Formprin.ServiceReferenceAutos.Autos[] ObtenerAutos() {
            Formprin.ServiceReferenceAutos.ObtenerAutosRequest inValue = new Formprin.ServiceReferenceAutos.ObtenerAutosRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.ObtenerAutosRequestBody();
            Formprin.ServiceReferenceAutos.ObtenerAutosResponse retVal = ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).ObtenerAutos(inValue);
            return retVal.Body.ObtenerAutosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ObtenerAutosResponse> Formprin.ServiceReferenceAutos.WebServiceAutosSoap.ObtenerAutosAsync(Formprin.ServiceReferenceAutos.ObtenerAutosRequest request) {
            return base.Channel.ObtenerAutosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ObtenerAutosResponse> ObtenerAutosAsync() {
            Formprin.ServiceReferenceAutos.ObtenerAutosRequest inValue = new Formprin.ServiceReferenceAutos.ObtenerAutosRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.ObtenerAutosRequestBody();
            return ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).ObtenerAutosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formprin.ServiceReferenceAutos.InsertarAutoResponse Formprin.ServiceReferenceAutos.WebServiceAutosSoap.InsertarAuto(Formprin.ServiceReferenceAutos.InsertarAutoRequest request) {
            return base.Channel.InsertarAuto(request);
        }
        
        public bool InsertarAuto(string _marca, string _modelo, string _anio_fabricacion, decimal _precio, string _color) {
            Formprin.ServiceReferenceAutos.InsertarAutoRequest inValue = new Formprin.ServiceReferenceAutos.InsertarAutoRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.InsertarAutoRequestBody();
            inValue.Body._marca = _marca;
            inValue.Body._modelo = _modelo;
            inValue.Body._anio_fabricacion = _anio_fabricacion;
            inValue.Body._precio = _precio;
            inValue.Body._color = _color;
            Formprin.ServiceReferenceAutos.InsertarAutoResponse retVal = ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).InsertarAuto(inValue);
            return retVal.Body.InsertarAutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.InsertarAutoResponse> Formprin.ServiceReferenceAutos.WebServiceAutosSoap.InsertarAutoAsync(Formprin.ServiceReferenceAutos.InsertarAutoRequest request) {
            return base.Channel.InsertarAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.InsertarAutoResponse> InsertarAutoAsync(string _marca, string _modelo, string _anio_fabricacion, decimal _precio, string _color) {
            Formprin.ServiceReferenceAutos.InsertarAutoRequest inValue = new Formprin.ServiceReferenceAutos.InsertarAutoRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.InsertarAutoRequestBody();
            inValue.Body._marca = _marca;
            inValue.Body._modelo = _modelo;
            inValue.Body._anio_fabricacion = _anio_fabricacion;
            inValue.Body._precio = _precio;
            inValue.Body._color = _color;
            return ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).InsertarAutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formprin.ServiceReferenceAutos.ModificarResponse Formprin.ServiceReferenceAutos.WebServiceAutosSoap.Modificar(Formprin.ServiceReferenceAutos.ModificarRequest request) {
            return base.Channel.Modificar(request);
        }
        
        public bool Modificar(string _id, string _marcaM, string _modeloM, string _anio_fabricacionM, decimal _precioM) {
            Formprin.ServiceReferenceAutos.ModificarRequest inValue = new Formprin.ServiceReferenceAutos.ModificarRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.ModificarRequestBody();
            inValue.Body._id = _id;
            inValue.Body._marcaM = _marcaM;
            inValue.Body._modeloM = _modeloM;
            inValue.Body._anio_fabricacionM = _anio_fabricacionM;
            inValue.Body._precioM = _precioM;
            Formprin.ServiceReferenceAutos.ModificarResponse retVal = ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).Modificar(inValue);
            return retVal.Body.ModificarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ModificarResponse> Formprin.ServiceReferenceAutos.WebServiceAutosSoap.ModificarAsync(Formprin.ServiceReferenceAutos.ModificarRequest request) {
            return base.Channel.ModificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ModificarResponse> ModificarAsync(string _id, string _marcaM, string _modeloM, string _anio_fabricacionM, decimal _precioM) {
            Formprin.ServiceReferenceAutos.ModificarRequest inValue = new Formprin.ServiceReferenceAutos.ModificarRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.ModificarRequestBody();
            inValue.Body._id = _id;
            inValue.Body._marcaM = _marcaM;
            inValue.Body._modeloM = _modeloM;
            inValue.Body._anio_fabricacionM = _anio_fabricacionM;
            inValue.Body._precioM = _precioM;
            return ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).ModificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formprin.ServiceReferenceAutos.EliminarAutoResponse Formprin.ServiceReferenceAutos.WebServiceAutosSoap.EliminarAuto(Formprin.ServiceReferenceAutos.EliminarAutoRequest request) {
            return base.Channel.EliminarAuto(request);
        }
        
        public bool EliminarAuto(string _id) {
            Formprin.ServiceReferenceAutos.EliminarAutoRequest inValue = new Formprin.ServiceReferenceAutos.EliminarAutoRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.EliminarAutoRequestBody();
            inValue.Body._id = _id;
            Formprin.ServiceReferenceAutos.EliminarAutoResponse retVal = ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).EliminarAuto(inValue);
            return retVal.Body.EliminarAutoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.EliminarAutoResponse> Formprin.ServiceReferenceAutos.WebServiceAutosSoap.EliminarAutoAsync(Formprin.ServiceReferenceAutos.EliminarAutoRequest request) {
            return base.Channel.EliminarAutoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.EliminarAutoResponse> EliminarAutoAsync(string _id) {
            Formprin.ServiceReferenceAutos.EliminarAutoRequest inValue = new Formprin.ServiceReferenceAutos.EliminarAutoRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.EliminarAutoRequestBody();
            inValue.Body._id = _id;
            return ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).EliminarAutoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Formprin.ServiceReferenceAutos.ObtenerMarcaResponse Formprin.ServiceReferenceAutos.WebServiceAutosSoap.ObtenerMarca(Formprin.ServiceReferenceAutos.ObtenerMarcaRequest request) {
            return base.Channel.ObtenerMarca(request);
        }
        
        public string ObtenerMarca(string _marca) {
            Formprin.ServiceReferenceAutos.ObtenerMarcaRequest inValue = new Formprin.ServiceReferenceAutos.ObtenerMarcaRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.ObtenerMarcaRequestBody();
            inValue.Body._marca = _marca;
            Formprin.ServiceReferenceAutos.ObtenerMarcaResponse retVal = ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).ObtenerMarca(inValue);
            return retVal.Body.ObtenerMarcaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ObtenerMarcaResponse> Formprin.ServiceReferenceAutos.WebServiceAutosSoap.ObtenerMarcaAsync(Formprin.ServiceReferenceAutos.ObtenerMarcaRequest request) {
            return base.Channel.ObtenerMarcaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Formprin.ServiceReferenceAutos.ObtenerMarcaResponse> ObtenerMarcaAsync(string _marca) {
            Formprin.ServiceReferenceAutos.ObtenerMarcaRequest inValue = new Formprin.ServiceReferenceAutos.ObtenerMarcaRequest();
            inValue.Body = new Formprin.ServiceReferenceAutos.ObtenerMarcaRequestBody();
            inValue.Body._marca = _marca;
            return ((Formprin.ServiceReferenceAutos.WebServiceAutosSoap)(this)).ObtenerMarcaAsync(inValue);
        }
    }
}
